# Generated by Django 4.0.3 on 2022-06-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usersapp',
        ),
    ]
